#!/usr/bin/env bash
set -euo pipefail

api_version='2023-03-01'

url="https://dev.api.affixapi.com/${api_version}" # dev
# url="https://api.affixapi.com/${api_version}" # prod

mode='xhr'
# mode='official'

token="${1:-''}" # pass your access token here as an argument or paste it between the single quotes

createemployee() {
  curl --fail \
    -H "Authorization: Bearer $token" \
    -H "Affix-Api-Origin: starter-kit" \
    -X POST \
    --data '{"first_name": "john", "last_name": "henry"}' \
    "${url}/${mode}/employee"
}

createemployee
