#!/usr/bin/env bash
set -euo pipefail

api_version='2023-03-01'

url="https://dev.api.affixapi.com/${api_version}" # dev
# url="https://api.affixapi.com/${api_version}" # prod

mode='developer'

token="${1:-''}" # pass your access token here as an argument or paste it between the single quotes

payruns() {
  local start_date='2023-11-01' # set this as you'd like
  local end_date='2023-11-30' # set this as you'd like

  curl --fail \
    -X GET \
    -H "Authorization: Bearer $token" \
    -H "Affix-Api-Origin: starter-kit" \
    "${url}/${mode}/payruns?start_date=${start_date}&end_date=${end_date}"
}

payruns
