name: pr

on:
  pull_request_target: # https://github.com/dependabot/dependabot-core/issues/3253
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write
  contents: write

jobs:
  sdk-example:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sdk-example

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # keep it as `secrets.GITHUB_TOKEN` as repo is public and this token has limited privs
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: sdk-example/.nvmrc
          cache: npm
          cache-dependency-path: sdk-example/package-lock.json

      - run: make ci

      - uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          working_directory: ./sdk-example
          dry_run: true
          semantic_version: 18
          extra_plugins: |
            @semantic-release/exec@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # keep it as `secrets.GITHUB_TOKEN` as repo is public and this token has limited privs

  jest-mocks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./jest-mocks

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # keep it as `secrets.GITHUB_TOKEN` as repo is public and this token has limited privs
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: jest-mocks/.nvmrc
          cache: npm
          cache-dependency-path: jest-mocks/package-lock.json

      - run: make ci

      - uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          working_directory: ./jest-mocks
          dry_run: true
          semantic_version: 18
          extra_plugins: |
            @semantic-release/exec@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # keep it as `secrets.GITHUB_TOKEN` as repo is public and this token has limited privs

  dependabot-approve-and-automerge:
    runs-on: ubuntu-latest
    needs:
      - sdk-example
      - jest-mocks
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: dependabot/fetch-metadata@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
